make the custom view transparent
AllanJuenemann/CalendarView pull request #2
Opened 2023-09-20 11:32 UTC by 343max

The custom view had a white background color which doens't look great when the calendar has a different background.

2023-09-24 18:23 UTC, AllanJuenemann requested changes

2023-09-24 18:23 UTC, AllanJuenemann commented on Sources/CalendarView/Decoration+SwiftUI.swift
Good catch. Thanks!
Could you please use tabs instead of spaces to indent the code properly?

2023-10-07 11:28 UTC, 343max commented on Sources/CalendarView/Decoration+SwiftUI.swift
Finally fixed it. Please review again.

2023-10-08 21:53 UTC, AllanJuenemann approved these changes

2023-10-08 21:56 UTC, merged